"""channel_events and replay_state

Revision ID: 43217dfb05e2
Revises: 634798e9a87c
Create Date: 2026-09-15 15:07:17.008479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '43217dfb05e2'
down_revision: Union[str, None] = '634798e9a87c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('replay_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('virtual_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('channel_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('is_alarm', sa.Boolean(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_events_channel_id'), 'channel_events', ['channel_id'], unique=False)
    op.create_index(op.f('ix_channel_events_event_time'), 'channel_events', ['event_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_channel_events_event_time'), table_name='channel_events')
    op.drop_index(op.f('ix_channel_events_channel_id'), table_name='channel_events')
    op.drop_table('channel_events')
    op.drop_table('replay_state')
    # ### end Alembic commands ###
