"""init

Revision ID: 634798e9a87c
Revises: 
Create Date: 2026-09-15 14:02:17.826317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '634798e9a87c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('device_type', sa.String(length=128), nullable=True),
    sa.Column('install_date', sa.DateTime(), nullable=True),
    sa.Column('last_maintenance_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_external_id'), 'devices', ['external_id'], unique=True)
    op.create_table('ingestion_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('rows_accepted', sa.Integer(), nullable=False),
    sa.Column('rows_rejected', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('sensor_types', sa.String(length=256), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('train_period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('train_period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('artifact_path', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('district', sa.String(length=128), nullable=True),
    sa.Column('kind', sa.String(length=64), nullable=True),
    sa.Column('hierarchy_level', sa.Integer(), nullable=True),
    sa.Column('geometry_wkt', sa.Text(), nullable=True),
    sa.Column('geometry_source', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['objects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_objects_external_id'), 'objects', ['external_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.Enum('dispatcher', 'analyst', 'admin', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=True),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('old_state', sa.JSON(), nullable=True),
    sa.Column('new_state', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_channel_id', sa.BigInteger(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('sensor_type', sa.String(length=128), nullable=False),
    sa.Column('subsystem', sa.String(length=128), nullable=True),
    sa.Column('location_tag', sa.String(length=128), nullable=True),
    sa.Column('location_group', sa.String(length=128), nullable=True),
    sa.Column('display_name', sa.String(length=256), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channels_external_channel_id'), 'channels', ['external_channel_id'], unique=True)
    op.create_index(op.f('ix_channels_location_group'), 'channels', ['location_group'], unique=False)
    op.create_index(op.f('ix_channels_location_tag'), 'channels', ['location_tag'], unique=False)
    op.create_index(op.f('ix_channels_sensor_type'), 'channels', ['sensor_type'], unique=False)
    op.create_table('incident_episodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('sensor_type', sa.String(length=128), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.Enum('sensor_state', 'dispatcher_confirmed', 'manual', name='episodesource'), nullable=False),
    sa.Column('is_flapping_incident', sa.Boolean(), nullable=False),
    sa.Column('left_censored', sa.Boolean(), nullable=False),
    sa.Column('right_censored', sa.Boolean(), nullable=False),
    sa.Column('label_policy_version', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_episodes_channel_id'), 'incident_episodes', ['channel_id'], unique=False)
    op.create_index(op.f('ix_incident_episodes_start_time'), 'incident_episodes', ['start_time'], unique=False)
    op.create_table('risk_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('new', 'observing', 'dispatched', 'rejected', 'resolved', name='riskcasestatus'), nullable=False),
    sa.Column('priority', sa.String(length=32), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_cases_channel_id'), 'risk_cases', ['channel_id'], unique=False)
    op.create_table('decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('risk_case_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('observe', 'dispatch', 'reject', 'clarify', name='decisionaction'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['risk_case_id'], ['risk_cases.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisions_risk_case_id'), 'decisions', ['risk_case_id'], unique=False)
    op.create_table('maintenance_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('risk_case_id', sa.Integer(), nullable=False),
    sa.Column('work_type', sa.String(length=128), nullable=False),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=32), nullable=True),
    sa.Column('recommended_by', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('draft', 'approved', 'in_progress', 'completed', 'rejected', 'cancelled', name='maintenancerequeststatus'), nullable=False),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['risk_case_id'], ['risk_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_requests_risk_case_id'), 'maintenance_requests', ['risk_case_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('risk_case_id', sa.Integer(), nullable=True),
    sa.Column('model_version_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('threshold_used', sa.Float(), nullable=True),
    sa.Column('explanation', sa.JSON(), nullable=True),
    sa.Column('data_quality_flag', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['risk_case_id'], ['risk_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_channel_id'), 'predictions', ['channel_id'], unique=False)
    op.create_index(op.f('ix_predictions_risk_case_id'), 'predictions', ['risk_case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_predictions_risk_case_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_channel_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_maintenance_requests_risk_case_id'), table_name='maintenance_requests')
    op.drop_table('maintenance_requests')
    op.drop_index(op.f('ix_decisions_risk_case_id'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_risk_cases_channel_id'), table_name='risk_cases')
    op.drop_table('risk_cases')
    op.drop_index(op.f('ix_incident_episodes_start_time'), table_name='incident_episodes')
    op.drop_index(op.f('ix_incident_episodes_channel_id'), table_name='incident_episodes')
    op.drop_table('incident_episodes')
    op.drop_index(op.f('ix_channels_sensor_type'), table_name='channels')
    op.drop_index(op.f('ix_channels_location_tag'), table_name='channels')
    op.drop_index(op.f('ix_channels_location_group'), table_name='channels')
    op.drop_index(op.f('ix_channels_external_channel_id'), table_name='channels')
    op.drop_table('channels')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_objects_external_id'), table_name='objects')
    op.drop_table('objects')
    op.drop_table('model_versions')
    op.drop_table('ingestion_runs')
    op.drop_index(op.f('ix_devices_external_id'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
