"""user_object_access

Revision ID: 6a9f6ccefc49
Revises: 43217dfb05e2
Create Date: 2026-09-15 17:30:35.145773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6a9f6ccefc49'
down_revision: Union[str, None] = '43217dfb05e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_object_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'object_id', name='uq_user_object_access')
    )
    op.create_index(op.f('ix_user_object_access_object_id'), 'user_object_access', ['object_id'], unique=False)
    op.create_index(op.f('ix_user_object_access_user_id'), 'user_object_access', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_object_access_user_id'), table_name='user_object_access')
    op.drop_index(op.f('ix_user_object_access_object_id'), table_name='user_object_access')
    op.drop_table('user_object_access')
    # ### end Alembic commands ###
